#!/usr/bin/env python3
"""Bake a subset of GNU Unifont (BDF) into a static Rust table for muse-render.

Output: deterministic, self-contained 16-row bitmap glyphs. Narrow glyphs are
8px wide (1 cell), wide glyphs 16px (2 cells). Each row stored as a u16,
MSB-aligned. Run once; the output is checked in.
"""
import sys

BDF = sys.argv[1]
OUT = sys.argv[2]

# Codepoints to bake: printable ASCII + common box-drawing/blocks + a few CJK.
wanted = set(range(0x20, 0x7F))
wanted |= {
    0x2500, 0x2502, 0x250C, 0x2510, 0x2514, 0x2518, 0x251C, 0x2524,
    0x252C, 0x2534, 0x253C,  # box drawing
    0x2588, 0x2591, 0x2592, 0x2593,  # blocks
    0x2190, 0x2191, 0x2192, 0x2193,  # arrows
    0x65E5, 0x672C, 0x754C, 0x6587,  # 日 本 界 文 (CJK, wide)
    0x2764,  # heart
}

glyphs = {}  # cp -> (width_cells, [16 rows as int])

ASCENT = 14  # unifont baseline: bbx yoff -2, height 16 => top at 14

with open(BDF, "r", encoding="latin-1") as f:
    cp = None
    bbx = None
    bitmap = None
    reading = False
    for line in f:
        line = line.rstrip("\n")
        if line.startswith("ENCODING"):
            cp = int(line.split()[1])
        elif line.startswith("BBX"):
            parts = line.split()
            bbx = (int(parts[1]), int(parts[2]), int(parts[3]), int(parts[4]))
        elif line.startswith("BITMAP"):
            bitmap = []
            reading = True
        elif line.startswith("ENDCHAR"):
            reading = False
            if cp in wanted and bbx is not None:
                w, h, xo, yo = bbx
                wide = w > 8
                cell_w = 2 if wide else 1
                rows = [0] * 16
                # bbx top in cell coords:
                top = ASCENT - (yo + h)
                for i, hexrow in enumerate(bitmap):
                    val = int(hexrow, 16)
                    nbits = len(hexrow) * 4
                    # left-align to 16-bit field
                    shifted = val << (16 - nbits)
                    # account for x offset
                    shifted >>= 0  # unifont xo is 0 for our set
                    cy = top + i
                    if 0 <= cy < 16:
                        rows[cy] |= shifted & 0xFFFF
                glyphs[cp] = (cell_w, rows)
            cp = None
            bbx = None
        elif reading:
            bitmap.append(line.strip())

with open(OUT, "w") as o:
    o.write("//! GENERATED by tools/gen_font.py from GNU Unifont. Do not edit.\n")
    o.write("//! Each glyph: 16 rows, MSB-aligned u16. width = cells (1 narrow, 2 wide).\n\n")
    o.write("/// (codepoint, width_cells, [16 rows]).\n")
    o.write("pub static GLYPHS: &[(u32, u8, [u16; 16])] = &[\n")
    for cp in sorted(glyphs):
        cw, rows = glyphs[cp]
        rowstr = ", ".join("0x%04x" % r for r in rows)
        o.write("    (0x%04x, %d, [%s]),\n" % (cp, cw, rowstr))
    o.write("];\n")

print("baked %d glyphs -> %s" % (len(glyphs), OUT))
